apiVersion: v1
kind: Secret
metadata:
  name: secret-db-{{ include "app-chart.name" . }}
data:
  username: {{ .Values.db.username | b64enc | quote }}
  password: {{ .Values.db.password | b64enc | quote }}