apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.name" . }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "app-chart.selectorLabels" . | nindent 4}}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: {{ .Values.service.name }}